# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'TEALAudienceStream' do
	pod 'TealiumUtilities'
end

target 'TEALAudienceStreamTests' do
	pod 'TealiumUtilities'
end

