# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'ASTester' do
    pod 'TealiumUtilities'
end

target 'ASTesterTests' do
    pod 'TealiumUtilities'
end

